#!/bin/bash
count=0
max_numbers=6000
while [ $count -lt $max_numbers ]; do
    random_num=$(jot -r 1 1 10000)
    if ! [[ $numbers =~ (^|[[:space:]])$random_num($|[[:space:]]) ]]; then
        if [ $count -gt 0 ]; then
            echo -n " "
        fi
        echo -n "$random_num"
        numbers+=" $random_num"
        ((count++))
    fi
done

